import type { AgentMetaMap } from "./types";

export const agentMeta: AgentMetaMap = {
  adal: {
    id: "adal",
    name: "AdaL",
    directory: ".adal/",
    rootFile: null,
    rules: null,
    commands: null,
    agents: null,
    skills: "skills/",
    mcp: "settings.json",
  },
  amp: {
    id: "amp",
    name: "Amp",
    directory: ".agents/",
    rootFile: null,
    rules: "checks/",
    commands: null,
    agents: null,
    skills: "skills/",
    mcp: ".amp/settings.json",
  },
  antigravity: {
    id: "antigravity",
    name: "Antigravity",
    directory: ".agent/",
    rootFile: null,
    rules: "rules/",
    commands: "workflows/",
    agents: null,
    skills: "skills/",
    mcp: null,
  },
  augment: {
    id: "augment",
    name: "Augment Code",
    directory: ".augment/",
    rootFile: null,
    rules: "rules/",
    commands: "commands/",
    agents: null,
    skills: "skills/",
    mcp: null,
  },
  claude: {
    id: "claude",
    name: "Claude Code",
    directory: ".claude/",
    rootFile: "CLAUDE.md",
    rules: "rules/",
    commands: "commands/",
    agents: "agents/",
    skills: "skills/",
    mcp: ".mcp.json (root)",
  },
  "claude-plugin": {
    id: "claude-plugin",
    name: "Claude Code Plugin",
    directory: ".claude-plugin/",
    rootFile: null,
    rules: "rules/",
    commands: "commands/",
    agents: "agents/",
    skills: "skills/",
    mcp: ".mcp.json (root)",
  },
  cline: {
    id: "cline",
    name: "Cline",
    directory: ".cline/",
    rootFile: null,
    rules: null,
    commands: null,
    agents: null,
    skills: "skills/",
    mcp: "cline_mcp_settings.json",
  },
  codebuddy: {
    id: "codebuddy",
    name: "CodeBuddy",
    directory: ".codebuddy/",
    rootFile: null,
    rules: "rules/",
    commands: null,
    agents: null,
    skills: "skills/",
    mcp: null,
  },
  codex: {
    id: "codex",
    name: "Codex CLI",
    directory: ".codex/",
    rootFile: null,
    rules: null,
    commands: "prompts/",
    agents: null,
    skills: "skills/",
    mcp: "config.toml",
  },
  "command-code": {
    id: "command-code",
    name: "Command Code",
    directory: ".commandcode/",
    rootFile: null,
    rules: null,
    commands: "commands/",
    agents: "agents/",
    skills: "skills/",
    mcp: null,
  },
  continue: {
    id: "continue",
    name: "Continue",
    directory: ".continue/",
    rootFile: null,
    rules: "rules/",
    commands: "prompts/",
    agents: null,
    skills: "skills/",
    mcp: null,
  },
  crush: {
    id: "crush",
    name: "Crush",
    directory: ".config/crush/",
    rootFile: null,
    rules: null,
    commands: null,
    agents: null,
    skills: "skills/",
    mcp: "crush.json (root)",
  },
  cursor: {
    id: "cursor",
    name: "Cursor",
    directory: ".cursor/",
    rootFile: null,
    rules: "rules/",
    commands: "commands/",
    agents: "agents/",
    skills: "skills/",
    mcp: "mcp.json",
  },
  factory: {
    id: "factory",
    name: "Factory AI",
    directory: ".factory/",
    rootFile: null,
    rules: null,
    commands: "commands/",
    agents: "droids/",
    skills: "skills/",
    mcp: "settings/mcp.json",
  },
  "github-copilot": {
    id: "github-copilot",
    name: "GitHub Copilot",
    directory: ".github/",
    rootFile: null,
    rules: null,
    commands: null,
    agents: "agents/",
    skills: "skills/",
    mcp: null,
  },
  goose: {
    id: "goose",
    name: "Goose",
    directory: ".goose/",
    rootFile: null,
    rules: null,
    commands: null,
    agents: null,
    skills: "skills/",
    mcp: "config.yaml",
  },
  iflow: {
    id: "iflow",
    name: "iFlow CLI",
    directory: ".iflow/",
    rootFile: "IFLOW.md",
    rules: null,
    commands: "commands/",
    agents: "agents/",
    skills: "skills/",
    mcp: "settings.json",
  },
  junie: {
    id: "junie",
    name: "Junie",
    directory: ".junie/",
    rootFile: null,
    rules: null,
    commands: null,
    agents: null,
    skills: "skills/",
    mcp: null,
  },
  kilo: {
    id: "kilo",
    name: "Kilo Code",
    directory: ".kilocode/",
    rootFile: null,
    rules: "rules/",
    commands: "workflows/",
    agents: null,
    skills: "skills/",
    mcp: "mcp.json",
  },
  kimi: {
    id: "kimi",
    name: "Kimi Code CLI",
    directory: ".agents/",
    rootFile: null,
    rules: null,
    commands: null,
    agents: null,
    skills: "skills/",
    mcp: ".kimi/mcp.json",
  },
  kiro: {
    id: "kiro",
    name: "Kiro",
    directory: ".kiro/",
    rootFile: null,
    rules: "steering/",
    commands: null,
    agents: null,
    skills: "skills/",
    mcp: "settings/mcp.json",
  },
  kode: {
    id: "kode",
    name: "Kode",
    directory: ".kode/",
    rootFile: null,
    rules: null,
    commands: null,
    agents: null,
    skills: "skills/",
    mcp: null,
  },
  mcpjam: {
    id: "mcpjam",
    name: "MCPJam",
    directory: ".mcpjam/",
    rootFile: null,
    rules: null,
    commands: null,
    agents: null,
    skills: "skills/",
    mcp: null,
  },
  mistral: {
    id: "mistral",
    name: "Mistral Vibe",
    directory: ".vibe/",
    rootFile: null,
    rules: null,
    commands: null,
    agents: null,
    skills: "skills/",
    mcp: null,
  },
  mux: {
    id: "mux",
    name: "Mux",
    directory: ".mux/",
    rootFile: null,
    rules: null,
    commands: null,
    agents: null,
    skills: "skills/",
    mcp: null,
  },
  neovate: {
    id: "neovate",
    name: "Neovate",
    directory: ".neovate/",
    rootFile: null,
    rules: null,
    commands: null,
    agents: null,
    skills: "skills/",
    mcp: "mcp.json",
  },
  openclaw: {
    id: "openclaw",
    name: "OpenClaw",
    directory: ".openclaw/",
    rootFile: null,
    rules: null,
    commands: null,
    agents: null,
    skills: "skills/",
    mcp: null,
  },
  opencode: {
    id: "opencode",
    name: "OpenCode",
    directory: ".opencode/",
    rootFile: null,
    rules: null,
    commands: "commands/",
    agents: "agents/",
    skills: "skills/",
    mcp: "opencode.json",
  },
  openhands: {
    id: "openhands",
    name: "OpenHands",
    directory: ".openhands/",
    rootFile: null,
    rules: null,
    commands: null,
    agents: null,
    skills: "skills/",
    mcp: "mcp.json",
  },
  "pi-mono": {
    id: "pi-mono",
    name: "Pi-Mono",
    directory: ".pi/",
    rootFile: null,
    rules: null,
    commands: "agent/prompts/",
    agents: null,
    skills: "agent/skills/",
    mcp: null,
  },
  pochi: {
    id: "pochi",
    name: "Pochi",
    directory: ".pochi/",
    rootFile: null,
    rules: null,
    commands: null,
    agents: null,
    skills: "skills/",
    mcp: null,
  },
  qoder: {
    id: "qoder",
    name: "Qoder",
    directory: ".qoder/",
    rootFile: null,
    rules: "rules/",
    commands: "commands/",
    agents: "agents/",
    skills: "skills/",
    mcp: null,
  },
  qwen: {
    id: "qwen",
    name: "Qwen Code",
    directory: ".qwen/",
    rootFile: "QWEN.md",
    rules: null,
    commands: null,
    agents: "agents/",
    skills: "skills/",
    mcp: "settings.json",
  },
  replit: {
    id: "replit",
    name: "Replit",
    directory: ".agents/",
    rootFile: "replit.md",
    rules: null,
    commands: null,
    agents: null,
    skills: "skills/",
    mcp: null,
  },
  roo: {
    id: "roo",
    name: "Roo Code",
    directory: ".roo/",
    rootFile: null,
    rules: null,
    commands: "commands/",
    agents: null,
    skills: "skills/",
    mcp: "mcp.json",
  },
  trae: {
    id: "trae",
    name: "Trae",
    directory: ".trae/",
    rootFile: null,
    rules: "rules/",
    commands: null,
    agents: null,
    skills: "skills/",
    mcp: null,
  },
  "trae-cn": {
    id: "trae-cn",
    name: "Trae CN",
    directory: ".trae-cn/",
    rootFile: null,
    rules: "rules/",
    commands: null,
    agents: null,
    skills: "skills/",
    mcp: null,
  },
  warp: {
    id: "warp",
    name: "Warp",
    directory: ".warp/",
    rootFile: "WARP.md",
    rules: null,
    commands: null,
    agents: null,
    skills: null,
    mcp: null,
  },
  windsurf: {
    id: "windsurf",
    name: "Windsurf",
    directory: ".windsurf/",
    rootFile: null,
    rules: "rules/",
    commands: null,
    agents: null,
    skills: "skills/",
    mcp: null,
  },
  zencoder: {
    id: "zencoder",
    name: "Zencoder",
    directory: ".zencoder/",
    rootFile: null,
    rules: null,
    commands: null,
    agents: null,
    skills: "skills/",
    mcp: null,
  },
};
