import type {
  AgentConflict,
  AgentGroup,
  AgentResource,
  DiscoveredAgent,
  ManagedAgent,
  McpResource,
  ResolvedAgentView,
  ResourceKind,
  SkillResource,
  SubagentResource,
} from "./types";

export const discoveredAgents: DiscoveredAgent[] = [
  {
    discoveryId: "discovery-cursor-workspace",
    fingerprint: "cursor-workspace-main",
    provider: "cursor",
    displayName: "Cursor",
    rootPath: ".cursor/",
    configPath: ".cursor/mcp.json",
    sourceScope: "workspace",
    status: "discovered",
    resourceCounts: { skill: 6, mcp: 1, subagent: 1 },
    detectedAt: "2026-03-25T10:20:00Z",
  },
  {
    discoveryId: "discovery-claude-user",
    fingerprint: "claude-user-default",
    provider: "claude",
    displayName: "Claude Code",
    rootPath: ".claude/",
    configPath: ".claude/settings.json",
    sourceScope: "user",
    status: "conflict",
    reason: "Workspace and user level configs were both detected.",
    resourceCounts: { skill: 6, mcp: 1, subagent: 1 },
    detectedAt: "2026-03-25T10:21:00Z",
  },
  {
    discoveryId: "discovery-codex-user",
    fingerprint: "codex-user-default",
    provider: "codex",
    displayName: "Codex CLI",
    rootPath: ".codex/",
    configPath: ".codex/config.toml",
    sourceScope: "user",
    status: "discovered",
    resourceCounts: { skill: 3, mcp: 1, subagent: 0 },
    detectedAt: "2026-03-25T10:22:00Z",
  },
  {
    discoveryId: "discovery-antigravity-manual",
    fingerprint: "antigravity-manual-default",
    provider: "antigravity",
    displayName: "Antigravity",
    rootPath: ".agent/",
    configPath: ".agent/config.json",
    sourceScope: "manual",
    status: "unreadable",
    reason: "AgentDock could not read one workflow file.",
    resourceCounts: { skill: 4, mcp: 0, subagent: 1 },
    detectedAt: "2026-03-25T10:23:00Z",
  },
];

export const managedAgents: ManagedAgent[] = [
  {
    managedAgentId: "managed-cursor",
    fingerprint: "cursor-workspace-main",
    enabled: true,
    hidden: false,
    importedAt: "2026-03-24T08:00:00Z",
    source: "auto-imported",
  },
  {
    managedAgentId: "managed-claude",
    fingerprint: "claude-user-default",
    alias: "Claude Main",
    enabled: true,
    hidden: false,
    importedAt: "2026-03-24T08:30:00Z",
    source: "manual-imported",
  },
  {
    managedAgentId: "managed-antigravity",
    fingerprint: "antigravity-manual-default",
    enabled: false,
    hidden: false,
    importedAt: "2026-03-24T09:00:00Z",
    source: "manual-imported",
  },
];

export const agentConflicts: AgentConflict[] = [
  {
    id: "conflict-claude-multi-source",
    type: "same-provider-multi-source",
    severity: "warning",
    summary: "Claude Code was found in both workspace and user scopes.",
    agentFingerprints: ["claude-user-default"],
    suggestedResolution: "ask-user",
  },
  {
    id: "conflict-antigravity-unreadable",
    type: "manual-vs-discovered",
    severity: "error",
    summary: "Antigravity contains an unreadable workflow file.",
    agentFingerprints: ["antigravity-manual-default"],
  },
];

export const resolvedAgents: ResolvedAgentView[] = [
  {
    id: "agent-cursor",
    discoveryId: "discovery-cursor-workspace",
    fingerprint: "cursor-workspace-main",
    provider: "cursor",
    name: "Cursor",
    role: "AI coding assistant",
    rootPath: ".cursor/",
    configPath: ".cursor/mcp.json",
    sourceScope: "workspace",
    managed: true,
    managedAgentId: "managed-cursor",
    enabled: true,
    hidden: false,
    health: "ok",
    status: "discovered",
    statusLabel: "Managed",
    summary: "Uses workspace level Cursor config and local tool resources.",
    groupId: "assistant",
    resourceCounts: { skill: 6, mcp: 1, subagent: 1 },
    conflictIds: [],
    lastScannedAt: "2026-03-25T10:20:00Z",
  },
  {
    id: "agent-claude-code",
    discoveryId: "discovery-claude-user",
    fingerprint: "claude-user-default",
    provider: "claude",
    name: "Claude Code",
    alias: "Claude Main",
    role: "CLI coding assistant",
    rootPath: ".claude/",
    configPath: ".claude/settings.json",
    sourceScope: "user",
    managed: true,
    managedAgentId: "managed-claude",
    enabled: true,
    hidden: false,
    health: "warning",
    status: "conflict",
    statusLabel: "Needs review",
    summary: "Uses shared Claude config with duplicated provider scope detected.",
    groupId: "assistant",
    resourceCounts: { skill: 6, mcp: 1, subagent: 1 },
    conflictIds: ["conflict-claude-multi-source"],
    lastScannedAt: "2026-03-25T10:21:00Z",
  },
  {
    id: "agent-codex-cli",
    discoveryId: "discovery-codex-user",
    fingerprint: "codex-user-default",
    provider: "codex",
    name: "Codex CLI",
    role: "Terminal coding assistant",
    rootPath: ".codex/",
    configPath: ".codex/config.toml",
    sourceScope: "user",
    managed: false,
    enabled: false,
    hidden: false,
    health: "ok",
    status: "discovered",
    statusLabel: "Discovered",
    summary: "Detected from user config and ready to import into AgentDock.",
    groupId: "assistant",
    resourceCounts: { skill: 3, mcp: 1, subagent: 0 },
    conflictIds: [],
    lastScannedAt: "2026-03-25T10:22:00Z",
  },
  {
    id: "agent-antigravity",
    discoveryId: "discovery-antigravity-manual",
    fingerprint: "antigravity-manual-default",
    provider: "antigravity",
    name: "Antigravity",
    role: "Workflow automation assistant",
    rootPath: ".agent/",
    configPath: ".agent/config.json",
    sourceScope: "manual",
    managed: true,
    managedAgentId: "managed-antigravity",
    enabled: false,
    hidden: false,
    health: "error",
    status: "unreadable",
    statusLabel: "Unreadable",
    summary: "Manual path is registered but one workflow file is unreadable.",
    groupId: "assistant",
    resourceCounts: { skill: 4, mcp: 0, subagent: 1 },
    conflictIds: ["conflict-antigravity-unreadable"],
    lastScannedAt: "2026-03-25T10:23:00Z",
  },
];

export const agentGroups: AgentGroup[] = [
  { id: "all", name: "All Agents", count: resolvedAgents.length },
  { id: "managed", name: "Managed", count: resolvedAgents.filter((agent) => agent.managed).length },
  {
    id: "discovered",
    name: "Discovered",
    count: resolvedAgents.filter((agent) => !agent.managed).length,
  },
  { id: "assistant", name: "Assistant", count: resolvedAgents.length },
];

export const agents = resolvedAgents;

export const skillResources: SkillResource[] = [
  {
    id: "skill-release-checklist",
    kind: "skill",
    name: "Release Checklist",
    summary: "Runs local release preparation steps with manual gates.",
    enabled: true,
    tags: ["workflow", "release"],
    usageCount: 12,
    updatedAt: "2026-03-22",
    markdown:
      "# Release Checklist\n\n- Verify version files\n- Run smoke checks\n- Prepare notes\n- Pause before push",
  },
  {
    id: "skill-prototype-review",
    kind: "skill",
    name: "Prototype Review",
    summary: "Audits layout consistency, spacing, and interaction states.",
    enabled: true,
    tags: ["ui", "review"],
    usageCount: 9,
    updatedAt: "2026-03-21",
    markdown:
      "# Prototype Review\n\nUse this skill to inspect hierarchy, spacing, and i18n coverage before handoff.",
  },
  {
    id: "skill-doc-sync",
    kind: "skill",
    name: "Doc Sync",
    summary: "Keeps feature docs aligned with implementation milestones.",
    enabled: false,
    tags: ["docs"],
    usageCount: 4,
    updatedAt: "2026-03-18",
    markdown: "# Doc Sync\n\nCompare feature docs with current code paths and list mismatches.",
  },
];

export const mcpResources: McpResource[] = [
  {
    id: "mcp-filesystem-local",
    kind: "mcp",
    name: "Filesystem Local",
    summary: "Accesses workspace files and metadata with local permissions.",
    enabled: true,
    endpoint: "stdio://filesystem-local",
    transport: "stdio",
    usageCount: 14,
    updatedAt: "2026-03-20",
    document:
      "# Filesystem Local\n\nProvides controlled file reads, writes, and glob access inside the workspace.",
    config: '{\n  "command": "pnpm",\n  "args": ["mcp:filesystem"],\n  "cwd": "~/workspace"\n}',
  },
  {
    id: "mcp-browser-inspect",
    kind: "mcp",
    name: "Browser Inspect",
    summary: "Captures DOM snapshots and interaction traces for debugging.",
    enabled: true,
    endpoint: "http://127.0.0.1:3030/mcp",
    transport: "http",
    usageCount: 7,
    updatedAt: "2026-03-19",
    document:
      "# Browser Inspect\n\nExposes page snapshots, console logs, and input automation for local test sessions.",
    config:
      '{\n  "url": "http://127.0.0.1:3030/mcp",\n  "headers": {\n    "x-project": "agentdock"\n  }\n}',
  },
  {
    id: "mcp-notes-index",
    kind: "mcp",
    name: "Notes Index",
    summary: "Searches indexed markdown notes and internal summaries.",
    enabled: false,
    endpoint: "stdio://notes-index",
    transport: "stdio",
    usageCount: 3,
    updatedAt: "2026-03-17",
    document: "# Notes Index\n\nReturns note matches ranked by recency and semantic relevance.",
    config: '{\n  "command": "node",\n  "args": ["./tools/notes-index.js"]\n}',
  },
];

export const subagentResources: SubagentResource[] = [
  {
    id: "subagent-ui-critic",
    kind: "subagent",
    name: "UI Critic",
    summary: "Reviews layouts against compact desktop UI patterns.",
    enabled: true,
    model: "claude-sonnet-4-6",
    usageCount: 11,
    updatedAt: "2026-03-22",
    prompt: "Inspect layout density, navigation clarity, and right-panel readability.",
    capabilities: ["layout review", "dark mode review", "state coverage"],
  },
  {
    id: "subagent-schema-audit",
    kind: "subagent",
    name: "Schema Audit",
    summary: "Checks typed mock data and API replacement readiness.",
    enabled: true,
    model: "claude-haiku-4-5-20251001",
    usageCount: 8,
    updatedAt: "2026-03-20",
    prompt: "Verify that mock structures can be swapped with server payloads later.",
    capabilities: ["type audit", "mock review"],
  },
  {
    id: "subagent-ops-shadow",
    kind: "subagent",
    name: "Ops Shadow",
    summary: "Simulates release and rollout handoff notes for human review.",
    enabled: false,
    model: "claude-opus-4-6",
    usageCount: 2,
    updatedAt: "2026-03-16",
    prompt: "Summarize rollout blockers, open checks, and likely owner actions.",
    capabilities: ["release notes", "handoff summary"],
  },
];

export const resourcesByKind: Record<ResourceKind, AgentResource[]> = {
  skill: skillResources,
  mcp: mcpResources,
  subagent: subagentResources,
};
