import type { ResourceDetail } from "./types";

export const resourceItems: ResourceDetail[] = [
  {
    id: "resource-skill-claude-code-guide",
    kind: "skill",
    name: "Claude Code Guide",
    summary: "Workspace helper for Claude Code commands, MCP wiring, and API usage.",
    version: "4.6.0",
    source: "Local Library",
    usedByCount: 18,
    updatedAt: "2026-03-24",
    tags: ["claude", "workflow"],
    markdown:
      "# Claude Code Guide\n\n- Explain slash commands\n- Review MCP config paths\n- Suggest agent choices\n- Clarify SDK and API usage",
  },
  {
    id: "resource-skill-shadcn",
    kind: "skill",
    name: "shadcn Manager",
    summary: "Project helper for adding, searching, and debugging shadcn/ui components.",
    version: "1.5.2",
    source: "Design Team",
    usedByCount: 11,
    updatedAt: "2026-03-23",
    tags: ["ui", "shadcn"],
    markdown:
      "# shadcn Manager\n\nSearch component docs, align project wrappers, and troubleshoot shadcn/ui usage.",
  },
  {
    id: "resource-mcp-context7",
    kind: "mcp",
    name: "Context7",
    summary: "Loads current library documentation and examples for coding tasks.",
    version: "2.3.1",
    source: "Core Team",
    usedByCount: 14,
    updatedAt: "2026-03-24",
    endpoint: "stdio://context7",
    transport: "stdio",
    document:
      "# Context7\n\nProvides up-to-date library documentation snippets and usage examples inside the workspace.",
    config: '{\n  "command": "npx",\n  "args": ["-y", "@upstash/context7-mcp"]\n}',
  },
  {
    id: "resource-mcp-playwright",
    kind: "mcp",
    name: "Playwright",
    summary: "Runs browser automation, screenshots, and page inspection flows.",
    version: "1.52.0",
    source: "QA Toolkit",
    usedByCount: 9,
    updatedAt: "2026-03-22",
    endpoint: "stdio://playwright",
    transport: "stdio",
    document:
      "# Playwright\n\nUseful for UI regression checks, screenshots, DOM inspection, and flow replay.",
    config: '{\n  "command": "npx",\n  "args": ["@playwright/mcp@latest"]\n}',
  },
  {
    id: "resource-subagent-explore",
    kind: "subagent",
    name: "Explore Agent",
    summary: "Fast repository explorer for file discovery, naming variants, and code lookup.",
    version: "1.8.0",
    source: "Local Library",
    usedByCount: 16,
    updatedAt: "2026-03-24",
    model: "claude-sonnet-4-6",
    prompt:
      "Search the codebase broadly, find matching files, and summarize implementation locations.",
    capabilities: ["file discovery", "keyword search", "codebase mapping"],
  },
  {
    id: "resource-subagent-planner",
    kind: "subagent",
    name: "Planner Agent",
    summary: "Creates implementation plans with file targets and trade-off notes.",
    version: "1.2.4",
    source: "Platform Team",
    usedByCount: 7,
    updatedAt: "2026-03-21",
    model: "claude-haiku-4-5-20251001",
    prompt: "Turn feature requests into step-by-step plans before coding starts.",
    capabilities: ["task breakdown", "implementation planning"],
  },
];
