import type { MarketplaceItem } from "./types";

export const marketplaceItems: MarketplaceItem[] = [
  {
    id: "market-skill-claude-code-guide",
    kind: "skill",
    name: "Claude Code Guide",
    author: "Anthropic",
    source: "Official Registry",
    version: "4.6.0",
    installs: 18640,
    updatedAt: "2026-03-24",
    installState: "installed",
    description:
      "Provides guided help for Claude Code workflows, slash commands, MCP configuration, and agent usage.",
    highlights: ["CLI guidance", "API references", "MCP setup"],
    url: "https://skills.sh/",
  },
  {
    id: "market-mcp-context7",
    kind: "mcp",
    name: "Context7",
    author: "Upstash",
    source: "Official Registry",
    version: "2.3.1",
    installs: 9420,
    updatedAt: "2026-03-24",
    installState: "install",
    description:
      "Connects official package documentation and usage snippets so agents can reference current APIs while coding.",
    highlights: ["Library docs", "Current examples", "Tool-friendly output"],
    url: "https://skills.sh/",
  },
  {
    id: "market-subagent-explore",
    kind: "subagent",
    name: "Explore Agent",
    author: "Anthropic",
    source: "Official Registry",
    version: "1.8.0",
    installs: 12810,
    updatedAt: "2026-03-24",
    installState: "update",
    description:
      "Optimized for broad repository exploration, keyword discovery, and answering codebase structure questions.",
    highlights: ["Wide search coverage", "Fast codebase scan", "Architecture lookup"],
    url: "https://skills.sh/",
  },
  {
    id: "market-skill-shadcn",
    kind: "skill",
    name: "shadcn Manager",
    author: "Community",
    source: "Community Mirror",
    version: "1.5.2",
    installs: 6110,
    updatedAt: "2026-03-23",
    installState: "install",
    description:
      "Provides component search, install guidance, preset support, and debugging help for shadcn/ui based apps.",
    highlights: ["Component lookup", "Preset support", "UI debugging"],
    url: "https://skills.sh/",
  },
  {
    id: "market-mcp-playwright",
    kind: "mcp",
    name: "Playwright",
    author: "Microsoft",
    source: "Community Mirror",
    version: "1.52.0",
    installs: 7740,
    updatedAt: "2026-03-22",
    installState: "installed",
    description:
      "Enables browser automation, screenshots, DOM inspection, and interaction playback for frontend validation.",
    highlights: ["Browser control", "Screenshots", "Flow replay"],
    url: "https://skills.sh/",
  },
  {
    id: "market-subagent-planner",
    kind: "subagent",
    name: "Planner Agent",
    author: "Anthropic",
    source: "Local Mirror",
    version: "1.2.4",
    installs: 3580,
    updatedAt: "2026-03-21",
    installState: "install",
    description:
      "Useful for turning broad product requests into concrete execution steps before touching code.",
    highlights: ["Task breakdown", "File mapping", "Approach comparison"],
    url: "https://skills.sh/",
  },
];
