import type { MarketplaceItem } from "./types";

export const marketplaceItems: MarketplaceItem[] = [
  {
    id: "market-skill-claude-code-guide",
    kind: "skill",
    name: "Claude Code Guide",
    summary: "Answers questions about Claude Code, SDK, API, and tool setup.",
    author: "Anthropic",
    source: "Official Registry",
    version: "4.6.0",
    downloads: 18640,
    updatedAt: "2026-03-24",
    installState: "installed",
    description:
      "Provides guided help for Claude Code workflows, slash commands, MCP configuration, and agent usage.",
    highlights: ["CLI guidance", "API references", "MCP setup"],
  },
  {
    id: "market-mcp-context7",
    kind: "mcp",
    name: "Context7",
    summary: "Fetches fresh library docs and examples directly into coding sessions.",
    author: "Upstash",
    source: "Official Registry",
    version: "2.3.1",
    downloads: 9420,
    updatedAt: "2026-03-24",
    installState: "install",
    description:
      "Connects official package documentation and usage snippets so agents can reference current APIs while coding.",
    highlights: ["Library docs", "Current examples", "Tool-friendly output"],
  },
  {
    id: "market-subagent-explore",
    kind: "subagent",
    name: "Explore Agent",
    summary: "Searches large codebases quickly across files, folders, and naming variants.",
    author: "Anthropic",
    source: "Official Registry",
    version: "1.8.0",
    downloads: 12810,
    updatedAt: "2026-03-24",
    installState: "update",
    description:
      "Optimized for broad repository exploration, keyword discovery, and answering codebase structure questions.",
    highlights: ["Wide search coverage", "Fast codebase scan", "Architecture lookup"],
  },
  {
    id: "market-skill-shadcn",
    kind: "skill",
    name: "shadcn Manager",
    summary: "Helps add, inspect, and troubleshoot shadcn/ui components in projects.",
    author: "Community",
    source: "Community Mirror",
    version: "1.5.2",
    downloads: 6110,
    updatedAt: "2026-03-23",
    installState: "install",
    description:
      "Provides component search, install guidance, preset support, and debugging help for shadcn/ui based apps.",
    highlights: ["Component lookup", "Preset support", "UI debugging"],
  },
  {
    id: "market-mcp-playwright",
    kind: "mcp",
    name: "Playwright",
    summary: "Controls browsers for UI verification, capture, and flow replay.",
    author: "Microsoft",
    source: "Community Mirror",
    version: "1.52.0",
    downloads: 7740,
    updatedAt: "2026-03-22",
    installState: "installed",
    description:
      "Enables browser automation, screenshots, DOM inspection, and interaction playback for frontend validation.",
    highlights: ["Browser control", "Screenshots", "Flow replay"],
  },
  {
    id: "market-subagent-planner",
    kind: "subagent",
    name: "Planner Agent",
    summary: "Breaks feature work into implementation steps with files and trade-offs.",
    author: "Anthropic",
    source: "Local Mirror",
    version: "1.2.4",
    downloads: 3580,
    updatedAt: "2026-03-21",
    installState: "install",
    description:
      "Useful for turning broad product requests into concrete execution steps before touching code.",
    highlights: ["Task breakdown", "File mapping", "Approach comparison"],
  },
];

export const marketplaceSources = [
  "All Sources",
  "Official Registry",
  "Community Mirror",
  "Local Mirror",
];
